//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTS.Site.WebService.VtsWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainObjectDto", Namespace="http://schemas.datacontract.org/2004/07/VTSWebService.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTS.Site.WebService.VtsWebService.AgentVersionDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTS.Site.WebService.VtsWebService.VehicleDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTS.Site.WebService.VtsWebService.SystemNewsDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTS.Site.WebService.VtsWebService.SystemNewsLocalizedDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTS.Site.WebService.VtsWebService.UserDto))]
    public partial class DomainObjectDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentVersionDto", Namespace="http://schemas.datacontract.org/2004/07/VTSWebService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class AgentVersionDto : VTS.Site.WebService.VtsWebService.DomainObjectDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DownloadLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReleasedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DownloadLink {
            get {
                return this.DownloadLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.DownloadLinkField, value) != true)) {
                    this.DownloadLinkField = value;
                    this.RaisePropertyChanged("DownloadLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReleasedDate {
            get {
                return this.ReleasedDateField;
            }
            set {
                if ((this.ReleasedDateField.Equals(value) != true)) {
                    this.ReleasedDateField = value;
                    this.RaisePropertyChanged("ReleasedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VersionString {
            get {
                return this.VersionStringField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionStringField, value) != true)) {
                    this.VersionStringField = value;
                    this.RaisePropertyChanged("VersionString");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleDto", Namespace="http://schemas.datacontract.org/2004/07/VTSWebService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class VehicleDto : VTS.Site.WebService.VtsWebService.DomainObjectDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductionYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegisteredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VinField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Manufacturer {
            get {
                return this.ManufacturerField;
            }
            set {
                if ((this.ManufacturerField.Equals(value) != true)) {
                    this.ManufacturerField = value;
                    this.RaisePropertyChanged("Manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((this.MileageField.Equals(value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductionYear {
            get {
                return this.ProductionYearField;
            }
            set {
                if ((this.ProductionYearField.Equals(value) != true)) {
                    this.ProductionYearField = value;
                    this.RaisePropertyChanged("ProductionYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegisteredDate {
            get {
                return this.RegisteredDateField;
            }
            set {
                if ((this.RegisteredDateField.Equals(value) != true)) {
                    this.RegisteredDateField = value;
                    this.RaisePropertyChanged("RegisteredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vin {
            get {
                return this.VinField;
            }
            set {
                if ((object.ReferenceEquals(this.VinField, value) != true)) {
                    this.VinField = value;
                    this.RaisePropertyChanged("Vin");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemNewsDto", Namespace="http://schemas.datacontract.org/2004/07/VTSWebService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SystemNewsDto : VTS.Site.WebService.VtsWebService.DomainObjectDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatePublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBlockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VTS.Site.WebService.VtsWebService.SystemNewsLocalizedDto[] SystemNewsLocalizedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatePublished {
            get {
                return this.DatePublishedField;
            }
            set {
                if ((this.DatePublishedField.Equals(value) != true)) {
                    this.DatePublishedField = value;
                    this.RaisePropertyChanged("DatePublished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBlocked {
            get {
                return this.IsBlockedField;
            }
            set {
                if ((this.IsBlockedField.Equals(value) != true)) {
                    this.IsBlockedField = value;
                    this.RaisePropertyChanged("IsBlocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VTS.Site.WebService.VtsWebService.SystemNewsLocalizedDto[] SystemNewsLocalized {
            get {
                return this.SystemNewsLocalizedField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemNewsLocalizedField, value) != true)) {
                    this.SystemNewsLocalizedField = value;
                    this.RaisePropertyChanged("SystemNewsLocalized");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemNewsLocalizedDto", Namespace="http://schemas.datacontract.org/2004/07/VTSWebService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SystemNewsLocalizedDto : VTS.Site.WebService.VtsWebService.DomainObjectDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewsContentTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SystemNewsIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewsContentText {
            get {
                return this.NewsContentTextField;
            }
            set {
                if ((object.ReferenceEquals(this.NewsContentTextField, value) != true)) {
                    this.NewsContentTextField = value;
                    this.RaisePropertyChanged("NewsContentText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SystemNewsId {
            get {
                return this.SystemNewsIdField;
            }
            set {
                if ((this.SystemNewsIdField.Equals(value) != true)) {
                    this.SystemNewsIdField = value;
                    this.RaisePropertyChanged("SystemNewsId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/VTSWebService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class UserDto : VTS.Site.WebService.VtsWebService.DomainObjectDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegisteredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegisteredDate {
            get {
                return this.RegisteredDateField;
            }
            set {
                if ((this.RegisteredDateField.Equals(value) != true)) {
                    this.RegisteredDateField = value;
                    this.RaisePropertyChanged("RegisteredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleInformationDto", Namespace="http://schemas.datacontract.org/2004/07/VTSWebService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class VehicleInformationDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VTS.Site.WebService.VtsWebService.EngineDto EngineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VTS.Site.WebService.VtsWebService.EngineDto Engine {
            get {
                return this.EngineField;
            }
            set {
                if ((object.ReferenceEquals(this.EngineField, value) != true)) {
                    this.EngineField = value;
                    this.RaisePropertyChanged("Engine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleModel {
            get {
                return this.VehicleModelField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleModelField, value) != true)) {
                    this.VehicleModelField = value;
                    this.RaisePropertyChanged("VehicleModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vin {
            get {
                return this.VinField;
            }
            set {
                if ((object.ReferenceEquals(this.VinField, value) != true)) {
                    this.VinField = value;
                    this.RaisePropertyChanged("Vin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EngineDto", Namespace="http://schemas.datacontract.org/2004/07/VTSWebService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class EngineDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VTS.Site.WebService.VtsWebService.EngineFamilyDto FamilyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FuelTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InjectionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VTS.Site.WebService.VtsWebService.EngineFamilyDto Family {
            get {
                return this.FamilyField;
            }
            set {
                if ((object.ReferenceEquals(this.FamilyField, value) != true)) {
                    this.FamilyField = value;
                    this.RaisePropertyChanged("Family");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FuelType {
            get {
                return this.FuelTypeField;
            }
            set {
                if ((this.FuelTypeField.Equals(value) != true)) {
                    this.FuelTypeField = value;
                    this.RaisePropertyChanged("FuelType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InjectionType {
            get {
                return this.InjectionTypeField;
            }
            set {
                if ((this.InjectionTypeField.Equals(value) != true)) {
                    this.InjectionTypeField = value;
                    this.RaisePropertyChanged("InjectionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EngineFamilyDto", Namespace="http://schemas.datacontract.org/2004/07/VTSWebService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class EngineFamilyDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VtsWebService.IVtsWebService")]
    public interface IVtsWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/CheckConnection", ReplyAction="http://tempuri.org/IVtsWebService/CheckConnectionResponse")]
        string CheckConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/CheckConnection", ReplyAction="http://tempuri.org/IVtsWebService/CheckConnectionResponse")]
        System.Threading.Tasks.Task<string> CheckConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/CheckUsernameAvailability", ReplyAction="http://tempuri.org/IVtsWebService/CheckUsernameAvailabilityResponse")]
        bool CheckUsernameAvailability(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/CheckUsernameAvailability", ReplyAction="http://tempuri.org/IVtsWebService/CheckUsernameAvailabilityResponse")]
        System.Threading.Tasks.Task<bool> CheckUsernameAvailabilityAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/AuthenticateUser", ReplyAction="http://tempuri.org/IVtsWebService/AuthenticateUserResponse")]
        VTS.Site.WebService.VtsWebService.UserDto AuthenticateUser(string login, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/AuthenticateUser", ReplyAction="http://tempuri.org/IVtsWebService/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.UserDto> AuthenticateUserAsync(string login, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetLastAgentVersion", ReplyAction="http://tempuri.org/IVtsWebService/GetLastAgentVersionResponse")]
        VTS.Site.WebService.VtsWebService.AgentVersionDto GetLastAgentVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetLastAgentVersion", ReplyAction="http://tempuri.org/IVtsWebService/GetLastAgentVersionResponse")]
        System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.AgentVersionDto> GetLastAgentVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/RegisterUser", ReplyAction="http://tempuri.org/IVtsWebService/RegisterUserResponse")]
        void RegisterUser(VTS.Site.WebService.VtsWebService.UserDto user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/RegisterUser", ReplyAction="http://tempuri.org/IVtsWebService/RegisterUserResponse")]
        System.Threading.Tasks.Task RegisterUserAsync(VTS.Site.WebService.VtsWebService.UserDto user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetUserRoleByUserId", ReplyAction="http://tempuri.org/IVtsWebService/GetUserRoleByUserIdResponse")]
        int GetUserRoleByUserId(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetUserRoleByUserId", ReplyAction="http://tempuri.org/IVtsWebService/GetUserRoleByUserIdResponse")]
        System.Threading.Tasks.Task<int> GetUserRoleByUserIdAsync(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetPartnersVehiclesCount", ReplyAction="http://tempuri.org/IVtsWebService/GetPartnersVehiclesCountResponse")]
        int GetPartnersVehiclesCount(long partnerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetPartnersVehiclesCount", ReplyAction="http://tempuri.org/IVtsWebService/GetPartnersVehiclesCountResponse")]
        System.Threading.Tasks.Task<int> GetPartnersVehiclesCountAsync(long partnerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetClientsForPartner", ReplyAction="http://tempuri.org/IVtsWebService/GetClientsForPartnerResponse")]
        VTS.Site.WebService.VtsWebService.UserDto[] GetClientsForPartner(string login, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetClientsForPartner", ReplyAction="http://tempuri.org/IVtsWebService/GetClientsForPartnerResponse")]
        System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.UserDto[]> GetClientsForPartnerAsync(string login, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetUsersVehicles", ReplyAction="http://tempuri.org/IVtsWebService/GetUsersVehiclesResponse")]
        VTS.Site.WebService.VtsWebService.VehicleDto[] GetUsersVehicles(string login, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetUsersVehicles", ReplyAction="http://tempuri.org/IVtsWebService/GetUsersVehiclesResponse")]
        System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.VehicleDto[]> GetUsersVehiclesAsync(string login, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetVehicleByVin", ReplyAction="http://tempuri.org/IVtsWebService/GetVehicleByVinResponse")]
        VTS.Site.WebService.VtsWebService.VehicleDto GetVehicleByVin(string vin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetVehicleByVin", ReplyAction="http://tempuri.org/IVtsWebService/GetVehicleByVinResponse")]
        System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.VehicleDto> GetVehicleByVinAsync(string vin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/CheckWhetherVinIsSupported", ReplyAction="http://tempuri.org/IVtsWebService/CheckWhetherVinIsSupportedResponse")]
        bool CheckWhetherVinIsSupported(string vin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/CheckWhetherVinIsSupported", ReplyAction="http://tempuri.org/IVtsWebService/CheckWhetherVinIsSupportedResponse")]
        System.Threading.Tasks.Task<bool> CheckWhetherVinIsSupportedAsync(string vin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetVehicleInformationByVin", ReplyAction="http://tempuri.org/IVtsWebService/GetVehicleInformationByVinResponse")]
        VTS.Site.WebService.VtsWebService.VehicleInformationDto GetVehicleInformationByVin(string vin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetVehicleInformationByVin", ReplyAction="http://tempuri.org/IVtsWebService/GetVehicleInformationByVinResponse")]
        System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.VehicleInformationDto> GetVehicleInformationByVinAsync(string vin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/ReturnUnsupportedVinsFromTheList", ReplyAction="http://tempuri.org/IVtsWebService/ReturnUnsupportedVinsFromTheListResponse")]
        string[] ReturnUnsupportedVinsFromTheList(string[] vins);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/ReturnUnsupportedVinsFromTheList", ReplyAction="http://tempuri.org/IVtsWebService/ReturnUnsupportedVinsFromTheListResponse")]
        System.Threading.Tasks.Task<string[]> ReturnUnsupportedVinsFromTheListAsync(string[] vins);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetAgentVersions", ReplyAction="http://tempuri.org/IVtsWebService/GetAgentVersionsResponse")]
        VTS.Site.WebService.VtsWebService.AgentVersionDto[] GetAgentVersions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetAgentVersions", ReplyAction="http://tempuri.org/IVtsWebService/GetAgentVersionsResponse")]
        System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.AgentVersionDto[]> GetAgentVersionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/NewsGetLast", ReplyAction="http://tempuri.org/IVtsWebService/NewsGetLastResponse")]
        VTS.Site.WebService.VtsWebService.SystemNewsDto[] NewsGetLast(int topCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/NewsGetLast", ReplyAction="http://tempuri.org/IVtsWebService/NewsGetLastResponse")]
        System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.SystemNewsDto[]> NewsGetLastAsync(int topCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/NewsGetAll", ReplyAction="http://tempuri.org/IVtsWebService/NewsGetAllResponse")]
        VTS.Site.WebService.VtsWebService.SystemNewsDto[] NewsGetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/NewsGetAll", ReplyAction="http://tempuri.org/IVtsWebService/NewsGetAllResponse")]
        System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.SystemNewsDto[]> NewsGetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/NewsGet", ReplyAction="http://tempuri.org/IVtsWebService/NewsGetResponse")]
        VTS.Site.WebService.VtsWebService.SystemNewsDto NewsGet(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/NewsGet", ReplyAction="http://tempuri.org/IVtsWebService/NewsGetResponse")]
        System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.SystemNewsDto> NewsGetAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/NewsUpdate", ReplyAction="http://tempuri.org/IVtsWebService/NewsUpdateResponse")]
        void NewsUpdate(VTS.Site.WebService.VtsWebService.SystemNewsDto item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/NewsUpdate", ReplyAction="http://tempuri.org/IVtsWebService/NewsUpdateResponse")]
        System.Threading.Tasks.Task NewsUpdateAsync(VTS.Site.WebService.VtsWebService.SystemNewsDto item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/NewsPersist", ReplyAction="http://tempuri.org/IVtsWebService/NewsPersistResponse")]
        void NewsPersist(VTS.Site.WebService.VtsWebService.SystemNewsDto item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/NewsPersist", ReplyAction="http://tempuri.org/IVtsWebService/NewsPersistResponse")]
        System.Threading.Tasks.Task NewsPersistAsync(VTS.Site.WebService.VtsWebService.SystemNewsDto item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/NewsDelete", ReplyAction="http://tempuri.org/IVtsWebService/NewsDeleteResponse")]
        void NewsDelete(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/NewsDelete", ReplyAction="http://tempuri.org/IVtsWebService/NewsDeleteResponse")]
        System.Threading.Tasks.Task NewsDeleteAsync(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVtsWebServiceChannel : VTS.Site.WebService.VtsWebService.IVtsWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VtsWebServiceClient : System.ServiceModel.ClientBase<VTS.Site.WebService.VtsWebService.IVtsWebService>, VTS.Site.WebService.VtsWebService.IVtsWebService {
        
        public VtsWebServiceClient() {
        }
        
        public VtsWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VtsWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VtsWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VtsWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckConnection() {
            return base.Channel.CheckConnection();
        }
        
        public System.Threading.Tasks.Task<string> CheckConnectionAsync() {
            return base.Channel.CheckConnectionAsync();
        }
        
        public bool CheckUsernameAvailability(string username) {
            return base.Channel.CheckUsernameAvailability(username);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUsernameAvailabilityAsync(string username) {
            return base.Channel.CheckUsernameAvailabilityAsync(username);
        }
        
        public VTS.Site.WebService.VtsWebService.UserDto AuthenticateUser(string login, string passwordHash) {
            return base.Channel.AuthenticateUser(login, passwordHash);
        }
        
        public System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.UserDto> AuthenticateUserAsync(string login, string passwordHash) {
            return base.Channel.AuthenticateUserAsync(login, passwordHash);
        }
        
        public VTS.Site.WebService.VtsWebService.AgentVersionDto GetLastAgentVersion() {
            return base.Channel.GetLastAgentVersion();
        }
        
        public System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.AgentVersionDto> GetLastAgentVersionAsync() {
            return base.Channel.GetLastAgentVersionAsync();
        }
        
        public void RegisterUser(VTS.Site.WebService.VtsWebService.UserDto user) {
            base.Channel.RegisterUser(user);
        }
        
        public System.Threading.Tasks.Task RegisterUserAsync(VTS.Site.WebService.VtsWebService.UserDto user) {
            return base.Channel.RegisterUserAsync(user);
        }
        
        public int GetUserRoleByUserId(long userId) {
            return base.Channel.GetUserRoleByUserId(userId);
        }
        
        public System.Threading.Tasks.Task<int> GetUserRoleByUserIdAsync(long userId) {
            return base.Channel.GetUserRoleByUserIdAsync(userId);
        }
        
        public int GetPartnersVehiclesCount(long partnerId) {
            return base.Channel.GetPartnersVehiclesCount(partnerId);
        }
        
        public System.Threading.Tasks.Task<int> GetPartnersVehiclesCountAsync(long partnerId) {
            return base.Channel.GetPartnersVehiclesCountAsync(partnerId);
        }
        
        public VTS.Site.WebService.VtsWebService.UserDto[] GetClientsForPartner(string login, string passwordHash) {
            return base.Channel.GetClientsForPartner(login, passwordHash);
        }
        
        public System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.UserDto[]> GetClientsForPartnerAsync(string login, string passwordHash) {
            return base.Channel.GetClientsForPartnerAsync(login, passwordHash);
        }
        
        public VTS.Site.WebService.VtsWebService.VehicleDto[] GetUsersVehicles(string login, string passwordHash) {
            return base.Channel.GetUsersVehicles(login, passwordHash);
        }
        
        public System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.VehicleDto[]> GetUsersVehiclesAsync(string login, string passwordHash) {
            return base.Channel.GetUsersVehiclesAsync(login, passwordHash);
        }
        
        public VTS.Site.WebService.VtsWebService.VehicleDto GetVehicleByVin(string vin) {
            return base.Channel.GetVehicleByVin(vin);
        }
        
        public System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.VehicleDto> GetVehicleByVinAsync(string vin) {
            return base.Channel.GetVehicleByVinAsync(vin);
        }
        
        public bool CheckWhetherVinIsSupported(string vin) {
            return base.Channel.CheckWhetherVinIsSupported(vin);
        }
        
        public System.Threading.Tasks.Task<bool> CheckWhetherVinIsSupportedAsync(string vin) {
            return base.Channel.CheckWhetherVinIsSupportedAsync(vin);
        }
        
        public VTS.Site.WebService.VtsWebService.VehicleInformationDto GetVehicleInformationByVin(string vin) {
            return base.Channel.GetVehicleInformationByVin(vin);
        }
        
        public System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.VehicleInformationDto> GetVehicleInformationByVinAsync(string vin) {
            return base.Channel.GetVehicleInformationByVinAsync(vin);
        }
        
        public string[] ReturnUnsupportedVinsFromTheList(string[] vins) {
            return base.Channel.ReturnUnsupportedVinsFromTheList(vins);
        }
        
        public System.Threading.Tasks.Task<string[]> ReturnUnsupportedVinsFromTheListAsync(string[] vins) {
            return base.Channel.ReturnUnsupportedVinsFromTheListAsync(vins);
        }
        
        public VTS.Site.WebService.VtsWebService.AgentVersionDto[] GetAgentVersions() {
            return base.Channel.GetAgentVersions();
        }
        
        public System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.AgentVersionDto[]> GetAgentVersionsAsync() {
            return base.Channel.GetAgentVersionsAsync();
        }
        
        public VTS.Site.WebService.VtsWebService.SystemNewsDto[] NewsGetLast(int topCount) {
            return base.Channel.NewsGetLast(topCount);
        }
        
        public System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.SystemNewsDto[]> NewsGetLastAsync(int topCount) {
            return base.Channel.NewsGetLastAsync(topCount);
        }
        
        public VTS.Site.WebService.VtsWebService.SystemNewsDto[] NewsGetAll() {
            return base.Channel.NewsGetAll();
        }
        
        public System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.SystemNewsDto[]> NewsGetAllAsync() {
            return base.Channel.NewsGetAllAsync();
        }
        
        public VTS.Site.WebService.VtsWebService.SystemNewsDto NewsGet(long id) {
            return base.Channel.NewsGet(id);
        }
        
        public System.Threading.Tasks.Task<VTS.Site.WebService.VtsWebService.SystemNewsDto> NewsGetAsync(long id) {
            return base.Channel.NewsGetAsync(id);
        }
        
        public void NewsUpdate(VTS.Site.WebService.VtsWebService.SystemNewsDto item) {
            base.Channel.NewsUpdate(item);
        }
        
        public System.Threading.Tasks.Task NewsUpdateAsync(VTS.Site.WebService.VtsWebService.SystemNewsDto item) {
            return base.Channel.NewsUpdateAsync(item);
        }
        
        public void NewsPersist(VTS.Site.WebService.VtsWebService.SystemNewsDto item) {
            base.Channel.NewsPersist(item);
        }
        
        public System.Threading.Tasks.Task NewsPersistAsync(VTS.Site.WebService.VtsWebService.SystemNewsDto item) {
            return base.Channel.NewsPersistAsync(item);
        }
        
        public void NewsDelete(long id) {
            base.Channel.NewsDelete(id);
        }
        
        public System.Threading.Tasks.Task NewsDeleteAsync(long id) {
            return base.Channel.NewsDeleteAsync(id);
        }
    }
}
