//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentVersion
    {
        public long Id { get; set; }
        public string VersionString { get; set; }
        public string DownloadLink { get; set; }
        public System.DateTime ReleasedDate { get; set; }
    }
}
