//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalyticStatisticsValue
    {
        public long Id { get; set; }
        public long AnalyticStatisticsItemId { get; set; }
        public double Value { get; set; }
        public string SourceVehicleVin { get; set; }
        public long SourcePsaParametersSetId { get; set; }
        public System.DateTime SourceDataCaptureDateTime { get; set; }
    
        public virtual AnalyticStatisticsItem AnalyticStatisticsItem { get; set; }
    }
}
