//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalyticRuleSettings
    {
        public AnalyticRuleSettings()
        {
            this.SettingsMolecule = new HashSet<SettingsMolecule>();
        }
    
        public long Id { get; set; }
        public int RuleType { get; set; }
        public Nullable<int> EngineFamilyType { get; set; }
        public Nullable<int> EngineType { get; set; }
        public int Reliability { get; set; }
    
        public virtual ICollection<SettingsMolecule> SettingsMolecule { get; set; }
    }
}
