//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        public long Id { get; set; }
        public int State { get; set; }
        public System.DateTime ServerDateIssued { get; set; }
        public int Type { get; set; }
        public int Period { get; set; }
        public long PartnerVehicleAssociationEntityLicenseEntity_LicenseEntity_Id { get; set; }
    
        public virtual UserVehicleAssociation UserVehicleAssociation { get; set; }
    }
}
