//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsaDataset
    {
        public PsaDataset()
        {
            this.PsaTrace = new HashSet<PsaTrace>();
        }
    
        public long Id { get; set; }
        public System.DateTime DateSaved { get; set; }
        public System.Guid Guid { get; set; }
        public System.DateTime DateExported { get; set; }
        public long VehicleEntityId { get; set; }
    
        public virtual ICollection<PsaTrace> PsaTrace { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
