//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsaParametersSet
    {
        public PsaParametersSet()
        {
            this.PsaParameterData = new HashSet<PsaParameterData>();
        }
    
        public long Id { get; set; }
        public long PsaTraceEntityId { get; set; }
        public int Type { get; set; }
        public string EcuName { get; set; }
        public string EcuLabel { get; set; }
        public string OriginalTypeId { get; set; }
        public string AdditionalSourceInfo { get; set; }
    
        public virtual ICollection<PsaParameterData> PsaParameterData { get; set; }
        public virtual PsaTrace PsaTrace { get; set; }
    }
}
