//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsaTrace
    {
        public PsaTrace()
        {
            this.PsaParametersSet = new HashSet<PsaParametersSet>();
        }
    
        public long Id { get; set; }
        public long PsaDatasetEntityId { get; set; }
        public System.DateTime Date { get; set; }
        public string Application { get; set; }
        public string Format { get; set; }
        public string Phone { get; set; }
        public string PhoneChannel { get; set; }
        public string Vin { get; set; }
        public string Address { get; set; }
        public string ToolSerialNumber { get; set; }
        public string SavesetId { get; set; }
        public int Mileage { get; set; }
        public int Manufacturer { get; set; }
        public string VehicleModelName { get; set; }
    
        public virtual PsaDataset PsaDataset { get; set; }
        public virtual ICollection<PsaParametersSet> PsaParametersSet { get; set; }
    }
}
