//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsAtom
    {
        public long Id { get; set; }
        public double MinOptimal { get; set; }
        public double MaxOptimal { get; set; }
        public double MinAcceptable { get; set; }
        public double MaxAcceptable { get; set; }
        public int Type { get; set; }
        public long SettingsMoleculeEntityId { get; set; }
    
        public virtual SettingsMolecule SettingsMolecule { get; set; }
    }
}
