//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsMolecule
    {
        public SettingsMolecule()
        {
            this.SettingsAtom = new HashSet<SettingsAtom>();
        }
    
        public long Id { get; set; }
        public bool OverrideOptimal { get; set; }
        public bool OverrideAcceptable { get; set; }
        public long AnalyticRuleSettingsEntityId { get; set; }
    
        public virtual AnalyticRuleSettings AnalyticRuleSettings { get; set; }
        public virtual ICollection<SettingsAtom> SettingsAtom { get; set; }
    }
}
