//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemNewsLocalized
    {
        public long Id { get; set; }
        public string Header { get; set; }
        public string NewsContentText { get; set; }
        public string Language { get; set; }
        public long SystemNewsId { get; set; }
    
        public virtual SystemNews SystemNews { get; set; }
    }
}
