//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemNews
    {
        public SystemNews()
        {
            this.SystemNewsLocalized = new HashSet<SystemNewsLocalized>();
        }
    
        public long Id { get; set; }
        public bool IsBlocked { get; set; }
        public System.DateTime DatePublished { get; set; }
    
        public virtual ICollection<SystemNewsLocalized> SystemNewsLocalized { get; set; }
    }
}
