//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVehicleAssociation
    {
        public UserVehicleAssociation()
        {
            this.License = new HashSet<License>();
        }
    
        public long Id { get; set; }
        public long VehicleEntityId { get; set; }
        public long UserEntityId { get; set; }
    
        public virtual ICollection<License> License { get; set; }
        public virtual User User { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
