//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserVehicleAssociation = new HashSet<UserVehicleAssociation>();
            this.UserProfile = new HashSet<UserProfile>();
            this.User1 = new HashSet<User>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string PasswordHash { get; set; }
        public string Login { get; set; }
        public string Surname { get; set; }
        public System.DateTime RegisteredDate { get; set; }
        public int Role { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<long> PrincipalId { get; set; }
    
        public virtual ICollection<UserVehicleAssociation> UserVehicleAssociation { get; set; }
        public virtual ICollection<UserProfile> UserProfile { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
