//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleCharacteristicsItemGroup
    {
        public VehicleCharacteristicsItemGroup()
        {
            this.VehicleCharacteristicsItem = new HashSet<VehicleCharacteristicsItem>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long VehicleCharacteristicsEntityId { get; set; }
    
        public virtual VehicleCharacteristics VehicleCharacteristics { get; set; }
        public virtual ICollection<VehicleCharacteristicsItem> VehicleCharacteristicsItem { get; set; }
    }
}
