//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.PsaDataset = new HashSet<PsaDataset>();
            this.UserVehicleAssociation = new HashSet<UserVehicleAssociation>();
            this.VehicleEvent = new HashSet<VehicleEvent>();
        }
    
        public long Id { get; set; }
        public string Vin { get; set; }
        public int Manufacturer { get; set; }
        public string ModelName { get; set; }
        public System.DateTime Registered { get; set; }
        public int ProductionYear { get; set; }
        public int Mileage { get; set; }
        public int Type { get; set; }
    
        public virtual ICollection<PsaDataset> PsaDataset { get; set; }
        public virtual ICollection<UserVehicleAssociation> UserVehicleAssociation { get; set; }
        public virtual ICollection<VehicleEvent> VehicleEvent { get; set; }
    }
}
