//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleEvent
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public int Mileage { get; set; }
        public int Type { get; set; }
        public Nullable<int> YellowMileage { get; set; }
        public Nullable<int> RedMileage { get; set; }
        public long VehicleEntityId { get; set; }
        public int NextReplacementPeriod { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
