//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleCharacteristics
    {
        public VehicleCharacteristics()
        {
            this.VehicleCharacteristicsItemGroup = new HashSet<VehicleCharacteristicsItemGroup>();
        }
    
        public long Id { get; set; }
        public string Language { get; set; }
        public string GeneralVehicleInfo { get; set; }
        public string Vin { get; set; }
    
        public virtual ICollection<VehicleCharacteristicsItemGroup> VehicleCharacteristicsItemGroup { get; set; }
    }
}
