//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWebService.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VTSDatabase : DbContext
    {
        public VTSDatabase()
            : base("name=VTSDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AnalyticRuleSettings> AnalyticRuleSettings { get; set; }
        public DbSet<AnalyticStatisticsItem> AnalyticStatisticsItem { get; set; }
        public DbSet<AnalyticStatisticsValue> AnalyticStatisticsValue { get; set; }
        public DbSet<License> License { get; set; }
        public DbSet<PsaDataset> PsaDataset { get; set; }
        public DbSet<PsaParameterData> PsaParameterData { get; set; }
        public DbSet<PsaParametersSet> PsaParametersSet { get; set; }
        public DbSet<PsaTrace> PsaTrace { get; set; }
        public DbSet<SettingsAtom> SettingsAtom { get; set; }
        public DbSet<SettingsMolecule> SettingsMolecule { get; set; }
        public DbSet<SystemNews> SystemNews { get; set; }
        public DbSet<SystemNewsLocalized> SystemNewsLocalized { get; set; }
        public DbSet<UnrecognizedVin> UnrecognizedVin { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserVehicleAssociation> UserVehicleAssociation { get; set; }
        public DbSet<Vehicle> Vehicle { get; set; }
        public DbSet<VehicleCharacteristics> VehicleCharacteristics { get; set; }
        public DbSet<VehicleCharacteristicsItem> VehicleCharacteristicsItem { get; set; }
        public DbSet<VehicleCharacteristicsItemGroup> VehicleCharacteristicsItemGroup { get; set; }
        public DbSet<VehicleEvent> VehicleEvent { get; set; }
        public DbSet<AgentVersion> AgentVersion { get; set; }
        public DbSet<UserProfile> UserProfile { get; set; }
    }
}
