//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Html {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Html.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:agentsystemrequirements.
        /// </summary>
        public static string AgentPrerequisitesWikiPage {
            get {
                return ResourceManager.GetString("AgentPrerequisitesWikiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisites.
        /// </summary>
        public static string AgentPrerequisitesWikiPageLinkText {
            get {
                return ResourceManager.GetString("AgentPrerequisitesWikiPageLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTS Agent prerequisites wiki page:.
        /// </summary>
        public static string AgentPrerequisitesWikiPageText {
            get {
                return ResourceManager.GetString("AgentPrerequisitesWikiPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:vtsagent.
        /// </summary>
        public static string AgentWikiPage {
            get {
                return ResourceManager.GetString("AgentWikiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTS Automonitoring.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Agent versions:.
        /// </summary>
        public static string AvailableAgentVersionsСolon {
            get {
                return ResourceManager.GetString("AvailableAgentVersionsСolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide monitoring service to your customers.
        /// </summary>
        public static string BannerFourHeader {
            get {
                return ResourceManager.GetString("BannerFourHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share vehicle diagnostic data analysis results with your customers using VTS Monitor web application..
        /// </summary>
        public static string BannerFourText1 {
            get {
                return ResourceManager.GetString("BannerFourText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenient viewing of data captured by your Lexia/DiagBox tool from your or your customer&apos;s vehicle..
        /// </summary>
        public static string BannerOneText1 {
            get {
                return ResourceManager.GetString("BannerOneText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch your car&apos;s state.
        /// </summary>
        public static string BannerThreeHeader {
            get {
                return ResourceManager.GetString("BannerThreeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles technical state analysis and monitoring based on chronologically supplied Lexia/Diagbox data..
        /// </summary>
        public static string BannerThreeText1 {
            get {
                return ResourceManager.GetString("BannerThreeText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexia/Diagbox integration..
        /// </summary>
        public static string BannerTwoHeader {
            get {
                return ResourceManager.GetString("BannerTwoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTS Agent. Convenient and instant view of data graphs captured from your vehicle by Lexia / DiagBox..
        /// </summary>
        public static string BannerTwoText1 {
            get {
                return ResourceManager.GetString("BannerTwoText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTS Automonitoring system.
        /// </summary>
        public static string BannerZeroHeader {
            get {
                return ResourceManager.GetString("BannerZeroHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of tools for car services and individuals aimed at monitoring your Peugeot/Citroen vehicle&apos;s technical state..
        /// </summary>
        public static string BannerZeroText1 {
            get {
                return ResourceManager.GetString("BannerZeroText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case the vehicle is compatible with the VTS Automonitoring, the system will identify the car model and the type of its engine..
        /// </summary>
        public static string CaseVinSupported {
            get {
                return ResourceManager.GetString("CaseVinSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your VIN compatibility with the system..
        /// </summary>
        public static string CheckYourVinCompatibilityInvitation {
            get {
                return ResourceManager.GetString("CheckYourVinCompatibilityInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic data capture.
        /// </summary>
        public static string DataCaptureHeader {
            get {
                return ResourceManager.GetString("DataCaptureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic data capture.
        /// </summary>
        public static string DataCaptureWikiPage {
            get {
                return ResourceManager.GetString("DataCaptureWikiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic data export.
        /// </summary>
        public static string DataExport {
            get {
                return ResourceManager.GetString("DataExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTS Agent.
        /// </summary>
        public static string DesktopApplicationName {
            get {
                return ResourceManager.GetString("DesktopApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details....
        /// </summary>
        public static string DetailsWithDots {
            get {
                return ResourceManager.GetString("DetailsWithDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download last version.
        /// </summary>
        public static string DownloadLastAgentVersion {
            get {
                return ResourceManager.GetString("DownloadLastAgentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string DownloadsDisplayName {
            get {
                return ResourceManager.GetString("DownloadsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTS Automonitoring 2013. All rights reserved.
        /// </summary>
        public static string FooterCopyrightText {
            get {
                return ResourceManager.GetString("FooterCopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTS Automonitoring 2013. All rights reserved..
        /// </summary>
        public static string FooterRightsReserved {
            get {
                return ResourceManager.GetString("FooterRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can i analyse this vehicle&apos;s diagnostic data?.
        /// </summary>
        public static string HowToProcessThisVehicleDiagnosticData {
            get {
                return ResourceManager.GetString("HowToProcessThisVehicleDiagnosticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More....
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon error. Please check your credentials..
        /// </summary>
        public static string LogOnErrorMessage {
            get {
                return ResourceManager.GetString("LogOnErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LogOnModelPassword {
            get {
                return ResourceManager.GetString("LogOnModelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string LogOnModelUsername {
            get {
                return ResourceManager.GetString("LogOnModelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:vtsautomonitoring.
        /// </summary>
        public static string MonitorWikiPage {
            get {
                return ResourceManager.GetString("MonitorWikiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic data analysis.
        /// </summary>
        public static string PageHeaderDataAnalysis {
            get {
                return ResourceManager.GetString("PageHeaderDataAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string PageHeaderDataAnalysis2 {
            get {
                return ResourceManager.GetString("PageHeaderDataAnalysis2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System&apos;s abilities.
        /// </summary>
        public static string PageHeaderDataAnalysis3 {
            get {
                return ResourceManager.GetString("PageHeaderDataAnalysis3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic data capture and view.
        /// </summary>
        public static string PageHeaderDataCapture {
            get {
                return ResourceManager.GetString("PageHeaderDataCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic data retrieval.
        /// </summary>
        public static string PageHeaderDataCapture2 {
            get {
                return ResourceManager.GetString("PageHeaderDataCapture2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the features of the free VTS Agent tool for easy viewing of diagnostic data obtained by Lexia / DiagBox..
        /// </summary>
        public static string PageHeaderDataCapture3 {
            get {
                return ResourceManager.GetString("PageHeaderDataCapture3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information at out Wiki:.
        /// </summary>
        public static string PageHeaderDataCapture4 {
            get {
                return ResourceManager.GetString("PageHeaderDataCapture4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providing data to the Client.
        /// </summary>
        public static string PageHeaderDataShare {
            get {
                return ResourceManager.GetString("PageHeaderDataShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration key creation and passing it to Client.
        /// </summary>
        public static string PageHeaderDataShare2 {
            get {
                return ResourceManager.GetString("PageHeaderDataShare2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string PageHeaderDataShare3 {
            get {
                return ResourceManager.GetString("PageHeaderDataShare3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current replacements.
        /// </summary>
        public static string PageHeaderDataShare4 {
            get {
                return ResourceManager.GetString("PageHeaderDataShare4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTS System overview.
        /// </summary>
        public static string PageHeaderSystemOverview {
            get {
                return ResourceManager.GetString("PageHeaderSystemOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After receiving the diagnostic data using Lexia / DiagBox and viewing them in the VTS Agent application, you can export the data to a file for later analysis using VTS Monitor web app..
        /// </summary>
        public static string PageTextDataAnalysis1 {
            get {
                return ResourceManager.GetString("PageTextDataAnalysis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web application VTS monitor stores and processes the diagnostic data of machines, and allows, based on them:.
        /// </summary>
        public static string PageTextDataAnalysis2 {
            get {
                return ResourceManager.GetString("PageTextDataAnalysis2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To participate in the VTS Monitor web application you will need to capture diagnostic data from vehicle and register a Partber account in the web app. You will be provided with a free trial 60 days license upon registration..
        /// </summary>
        public static string PageTextDataAnalysis3 {
            get {
                return ResourceManager.GetString("PageTextDataAnalysis3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system determines the type of vehicle&apos;s engine and compares the parameters of all vehicle systems to reference values​​, as well as to those of other similar vehicles, and then outputs the evaluation of vehicle systems&apos; state..
        /// </summary>
        public static string PageTextDataAnalysis4 {
            get {
                return ResourceManager.GetString("PageTextDataAnalysis4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate the current state of the vehicle.
        /// </summary>
        public static string PageTextDataAnalysisListItem1 {
            get {
                return ResourceManager.GetString("PageTextDataAnalysisListItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow vehicle parameters evolution in time.
        /// </summary>
        public static string PageTextDataAnalysisListItem2 {
            get {
                return ResourceManager.GetString("PageTextDataAnalysisListItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow the terms of the current replacements.
        /// </summary>
        public static string PageTextDataAnalysisListItem3 {
            get {
                return ResourceManager.GetString("PageTextDataAnalysisListItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:vtsautomonitoring.
        /// </summary>
        public static string PageTextDataAnalysisWikiItem1Link {
            get {
                return ResourceManager.GetString("PageTextDataAnalysisWikiItem1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTS Monitor web app.
        /// </summary>
        public static string PageTextDataAnalysisWikiItem1Text {
            get {
                return ResourceManager.GetString("PageTextDataAnalysisWikiItem1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:kickstart.
        /// </summary>
        public static string PageTextDataAnalysisWikiItem2Link {
            get {
                return ResourceManager.GetString("PageTextDataAnalysisWikiItem2Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to start working with the system.
        /// </summary>
        public static string PageTextDataAnalysisWikiItem2Text {
            get {
                return ResourceManager.GetString("PageTextDataAnalysisWikiItem2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:vtsfileformat.
        /// </summary>
        public static string PageTextDataAnalysisWikiItem3Link {
            get {
                return ResourceManager.GetString("PageTextDataAnalysisWikiItem3Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is .vts file.
        /// </summary>
        public static string PageTextDataAnalysisWikiItem3Text {
            get {
                return ResourceManager.GetString("PageTextDataAnalysisWikiItem3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic data is captured from the Peugeot / Citroen vehicle using the Lexia / DiagBox diagnostic kit. Please refer to our wiki to learn how to capture data that is optimal for processing through a VTS Automonitoring system..
        /// </summary>
        public static string PageTextDataCapture1 {
            get {
                return ResourceManager.GetString("PageTextDataCapture1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexia / DiagBox toolset does not provide a convenient tool to view captured diagnostic data. Use free VTS Agent tool to view captured data and to process it in VTS Monitor web application to get your customers&apos; vehicles parameters quality estimation..
        /// </summary>
        public static string PageTextDataCapture2 {
            get {
                return ResourceManager.GetString("PageTextDataCapture2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are two account types in the VTS Monitor system: .
        /// </summary>
        public static string PageTextDataShare1 {
            get {
                return ResourceManager.GetString("PageTextDataShare1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In terms of the VTS system Avtomonitoring partner is the owner of Lexia / DiagBox diagnostic system that serves the client machine. Accordingly, the client - the owner of the machine serviced by the Partner..
        /// </summary>
        public static string PageTextDataShare2 {
            get {
                return ResourceManager.GetString("PageTextDataShare2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration key is generated by the Partner using the VTS Monitor application, and can be sent to the Customer by phone, e-mail or in any other convenient manner..
        /// </summary>
        public static string PageTextDataShare4 {
            get {
                return ResourceManager.GetString("PageTextDataShare4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner pays for the VTS Automonitoring system service. Fees are charged for the purchase of licenses that have an expiration date. One license allows you to maintain a single vehicle. Partner charges a service fee to the customer, so reselling their services to the Client. Payments are made to the system by WebMoney or cash. The estimated cost of services is from 3 to 10 dollars a month for one car..
        /// </summary>
        public static string PageTextDataShare5 {
            get {
                return ResourceManager.GetString("PageTextDataShare5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners and customers can contribute and update information on the current replacements made​​. The system will report the occurrence of the next term of the current replacement..
        /// </summary>
        public static string PageTextDataShare6 {
            get {
                return ResourceManager.GetString("PageTextDataShare6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string PageTextDataShareListItem1 {
            get {
                return ResourceManager.GetString("PageTextDataShareListItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string PageTextDataShareListItem2 {
            get {
                return ResourceManager.GetString("PageTextDataShareListItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:partner.
        /// </summary>
        public static string PageTextDataShareWikiItem1Link {
            get {
                return ResourceManager.GetString("PageTextDataShareWikiItem1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:partner.
        /// </summary>
        public static string PageTextDataShareWikiItem1Link1 {
            get {
                return ResourceManager.GetString("PageTextDataShareWikiItem1Link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string PageTextDataShareWikiItem1Text {
            get {
                return ResourceManager.GetString("PageTextDataShareWikiItem1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:client.
        /// </summary>
        public static string PageTextDataShareWikiItem2Link {
            get {
                return ResourceManager.GetString("PageTextDataShareWikiItem2Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string PageTextDataShareWikiItem2Text {
            get {
                return ResourceManager.GetString("PageTextDataShareWikiItem2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:registrationkey.
        /// </summary>
        public static string PageTextDataShareWikiItem3Link {
            get {
                return ResourceManager.GetString("PageTextDataShareWikiItem3Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration key.
        /// </summary>
        public static string PageTextDataShareWikiItem3Text {
            get {
                return ResourceManager.GetString("PageTextDataShareWikiItem3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:license.
        /// </summary>
        public static string PageTextDataShareWikiItem4Link {
            get {
                return ResourceManager.GetString("PageTextDataShareWikiItem4Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string PageTextDataShareWikiItem4Text {
            get {
                return ResourceManager.GetString("PageTextDataShareWikiItem4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:navigatablepagedata.
        /// </summary>
        public static string PageTextDataShareWikiItem5Link {
            get {
                return ResourceManager.GetString("PageTextDataShareWikiItem5Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current replacements monitoring system.
        /// </summary>
        public static string PageTextDataShareWikiItem5Text {
            get {
                return ResourceManager.GetString("PageTextDataShareWikiItem5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:prices.
        /// </summary>
        public static string PageTextDataShareWikiItem6Link {
            get {
                return ResourceManager.GetString("PageTextDataShareWikiItem6Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service prices.
        /// </summary>
        public static string PageTextDataShareWikiItem6Text {
            get {
                return ResourceManager.GetString("PageTextDataShareWikiItem6Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:registrationkey.
        /// </summary>
        public static string RegistrationKeyWikiLink {
            get {
                return ResourceManager.GetString("RegistrationKeyWikiLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data capture.
        /// </summary>
        public static string Step1Caption {
            get {
                return ResourceManager.GetString("Step1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture vehicle data using your Lexia. Then preview them and export to a .vts file using VTS Agent free tool..
        /// </summary>
        public static string Step1Text {
            get {
                return ResourceManager.GetString("Step1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data analysis.
        /// </summary>
        public static string Step2Caption {
            get {
                return ResourceManager.GetString("Step2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload captured data to the VTS Monitor web application to analyse vehicle state..
        /// </summary>
        public static string Step2Text {
            get {
                return ResourceManager.GetString("Step2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass results to Client.
        /// </summary>
        public static string Step3Caption {
            get {
                return ResourceManager.GetString("Step3Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your client with his vehicle data and analysis results using a registration key..
        /// </summary>
        public static string Step3Text {
            get {
                return ResourceManager.GetString("Step3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automonitoring system.
        /// </summary>
        public static string SystemOverviewHeader1 {
            get {
                return ResourceManager.GetString("SystemOverviewHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reselling the Automonitoring service.
        /// </summary>
        public static string SystemOverviewHeader2 {
            get {
                return ResourceManager.GetString("SystemOverviewHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN Check.
        /// </summary>
        public static string SystemOverviewHeader3 {
            get {
                return ResourceManager.GetString("SystemOverviewHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System components.
        /// </summary>
        public static string SystemOverviewHeader4 {
            get {
                return ResourceManager.GetString("SystemOverviewHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;VTS Automonitoring&lt;/b&gt; is an innovative system designed for car services and individual businessmen which allows to monitor and evaluate changes in car systems parameters for Peugeot / Citroen vehicles over a long period of observation. The system can evaluate different vehicle systems state, primarily engine systems..
        /// </summary>
        public static string SystemOverviewText1 {
            get {
                return ResourceManager.GetString("SystemOverviewText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is specially designed for the automonitoring service resale. &lt;a href=&quot;http://vtsautomonitoring.wikidot.com/wiki:partner&quot;&gt;Partners&lt;/a&gt; around the world can use the system to evaluate the parameters of their &lt;a href=&quot;http://vtsautomonitoring.wikidot.com/wiki:client&quot;&gt;Clients&lt;/a&gt; Peugeot/Citroen vehicles and easily share analysis results of the analysis withtheir customers to gain a competitive advantage in the field of vehicle diagnostics and service. &lt;a href=&quot;http://vtsautomonitoring.wikidot.com/wi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SystemOverviewText2 {
            get {
                return ResourceManager.GetString("SystemOverviewText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can check your vehicle for compatibility with the system. If the test is passed then this machine can be serviced by the system and you can get evaluation of its diagnostic data. You will need the vehicle&apos;s VIN to do a compatibility check. &lt;a href=&quot;http://vtsautomonitoring.wikidot.com/wiki:vincheck&quot;&gt;Check the VIN...&lt;/a&gt;.
        /// </summary>
        public static string SystemOverviewText3 {
            get {
                return ResourceManager.GetString("SystemOverviewText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  — free application for easy and convenient view and export of diagnostic data obtained using Lexia / Diagbox diagnostic kit..
        /// </summary>
        public static string SystemOverviewText4 {
            get {
                return ResourceManager.GetString("SystemOverviewText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  — web application for organizing and analysis of the data obtained using VTS Agent..
        /// </summary>
        public static string SystemOverviewText5 {
            get {
                return ResourceManager.GetString("SystemOverviewText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  — a repository of information about the effective use of VTS Aгtomonitoring..
        /// </summary>
        public static string SystemOverviewText6 {
            get {
                return ResourceManager.GetString("SystemOverviewText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you can not find the information you need on the wiki or have any abnormal behavior of the system, please contact technical support at vtsautomonitoring@gmail.com..
        /// </summary>
        public static string SystemOverviewText7 {
            get {
                return ResourceManager.GetString("SystemOverviewText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical support.
        /// </summary>
        public static string TechnicalSupport {
            get {
                return ResourceManager.GetString("TechnicalSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string TechSupport {
            get {
                return ResourceManager.GetString("TechSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic data analysis.
        /// </summary>
        public static string TopicDetailsHeaderDataAnalysis {
            get {
                return ResourceManager.GetString("TopicDetailsHeaderDataAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data capture.
        /// </summary>
        public static string TopicDetailsHeaderDataCapture {
            get {
                return ResourceManager.GetString("TopicDetailsHeaderDataCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately the system could not get data for this VIN..
        /// </summary>
        public static string UnableToGetVehicleData {
            get {
                return ResourceManager.GetString("UnableToGetVehicleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately only Citroen, Peugeot and Opel vehicles are supported. Please contact our Support if you have questions on other manufacturers..
        /// </summary>
        public static string UnsupportedManufacturerMessage {
            get {
                return ResourceManager.GetString("UnsupportedManufacturerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation required.
        /// </summary>
        public static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately this vehicle is not supported. We have picked you your VIN to include in support, please follow our news..
        /// </summary>
        public static string VehiclenotSupportedText {
            get {
                return ResourceManager.GetString("VehiclenotSupportedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle recognized: {0}, engine: {1}. {2}.
        /// </summary>
        public static string VehicleRecognizedMessageFormat {
            get {
                return ResourceManager.GetString("VehicleRecognizedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:vincheck.
        /// </summary>
        public static string VinCheckWikiPage {
            get {
                return ResourceManager.GetString("VinCheckWikiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN must consist of 17 numbers and letters..
        /// </summary>
        public static string VinLengthErrorText {
            get {
                return ResourceManager.GetString("VinLengthErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTS Agent.
        /// </summary>
        public static string VtsAgent {
            get {
                return ResourceManager.GetString("VtsAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTS Agent application.
        /// </summary>
        public static string VtsAgentApplication {
            get {
                return ResourceManager.GetString("VtsAgentApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTS Agent is a tool for diagnostic data initial analysis and export to be later consumed by VTS Monitor application for further analysis..
        /// </summary>
        public static string VtsAgentExplanationHeader {
            get {
                return ResourceManager.GetString("VtsAgentExplanationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTS Мonitor.
        /// </summary>
        public static string VtsMonitor {
            get {
                return ResourceManager.GetString("VtsMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTS Monitor.
        /// </summary>
        public static string WebApplicationName {
            get {
                return ResourceManager.GetString("WebApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string WikiDisplayName {
            get {
                return ResourceManager.GetString("WikiDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/.
        /// </summary>
        public static string WikiLink {
            get {
                return ResourceManager.GetString("WikiLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:vtsagent.
        /// </summary>
        public static string WikiPageLinkAgent {
            get {
                return ResourceManager.GetString("WikiPageLinkAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:datacapture.
        /// </summary>
        public static string WikiPageLinkDataCapture {
            get {
                return ResourceManager.GetString("WikiPageLinkDataCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:dataexport.
        /// </summary>
        public static string WikiPageLinkDataExport {
            get {
                return ResourceManager.GetString("WikiPageLinkDataExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:support.
        /// </summary>
        public static string WikiPageLinkSupport {
            get {
                return ResourceManager.GetString("WikiPageLinkSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vtsautomonitoring.wikidot.com/wiki:vtsagent.
        /// </summary>
        public static string WikiPageLinkVtsAgent {
            get {
                return ResourceManager.GetString("WikiPageLinkVtsAgent", resourceCulture);
            }
        }
    }
}
