//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWeb.Presentation.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTSWeb.Presentation.Common.Resources.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активирована.
        /// </summary>
        public static string ActivatedText {
            get {
                return ResourceManager.GetString("ActivatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес:.
        /// </summary>
        public static string AddressColonText {
            get {
                return ResourceManager.GetString("AddressColonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string AddressText {
            get {
                return ResourceManager.GetString("AddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to После регистрации машины вы сможете сохранять для неё данные, вносить записи о событиях (заменах деталей, проведённых ТО и т.д.) и просматривать её статистические и хронологические параметры.
        /// </summary>
        public static string AfterVehicleRegisteredMessage {
            get {
                return ResourceManager.GetString("AfterVehicleRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аннулировать.
        /// </summary>
        public static string AnnulateText {
            get {
                return ResourceManager.GetString("AnnulateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Консоль управления данными.
        /// </summary>
        public static string AppHeader {
            get {
                return ResourceManager.GetString("AppHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string BackText {
            get {
                return ResourceManager.GetString("BackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (исходя из данных загруженного файла).
        /// </summary>
        public static string BasedOnFileLabel {
            get {
                return ResourceManager.GetString("BasedOnFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокировать.
        /// </summary>
        public static string BlockText {
            get {
                return ResourceManager.GetString("BlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аннулировать.
        /// </summary>
        public static string CancelKeyButtonText {
            get {
                return ResourceManager.GetString("CancelKeyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте правильность данных.
        /// </summary>
        public static string CheckDataConsistency {
            get {
                return ResourceManager.GetString("CheckDataConsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка данных перед сохранением.
        /// </summary>
        public static string CheckingImportableData {
            get {
                return ResourceManager.GetString("CheckingImportableData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте доступность имени чтобы продолжить регистрацию.
        /// </summary>
        public static string CheckLoginAvailabilityMessage {
            get {
                return ResourceManager.GetString("CheckLoginAvailabilityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to проверить.
        /// </summary>
        public static string CheckLoginText {
            get {
                return ResourceManager.GetString("CheckLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to проверить.
        /// </summary>
        public static string CheckText {
            get {
                return ResourceManager.GetString("CheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Пояснительный текст к параметру&gt;.
        /// </summary>
        public static string ChronoParameterIdleRpmColdExplanatoryText {
            get {
                return ResourceManager.GetString("ChronoParameterIdleRpmColdExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Холодный старт.
        /// </summary>
        public static string ChronoParameterIdleRpmColdText {
            get {
                return ResourceManager.GetString("ChronoParameterIdleRpmColdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Пояснительный текст к параметру&gt;.
        /// </summary>
        public static string ChronoParameterIdleRpmHotExplanatoryText {
            get {
                return ResourceManager.GetString("ChronoParameterIdleRpmHotExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Горячий старт.
        /// </summary>
        public static string ChronoParameterIdleRpmHotText {
            get {
                return ResourceManager.GetString("ChronoParameterIdleRpmHotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Пояснительный текст к параметру&gt;.
        /// </summary>
        public static string ChronoParameterIdleRpmMediumExplanatoryText {
            get {
                return ResourceManager.GetString("ChronoParameterIdleRpmMediumExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средний старт.
        /// </summary>
        public static string ChronoParameterIdleRpmMediumText {
            get {
                return ResourceManager.GetString("ChronoParameterIdleRpmMediumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двигатель.
        /// </summary>
        public static string ChronoParamGroupDisplayNameEngine {
            get {
                return ResourceManager.GetString("ChronoParamGroupDisplayNameEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двигатель – Впрыск.
        /// </summary>
        public static string ChronoParamGroupDisplayNameEngineInjection {
            get {
                return ResourceManager.GetString("ChronoParamGroupDisplayNameEngineInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обороты холостого хода.
        /// </summary>
        public static string ChronoParamTypeDisplayNameIdleEngineRpm {
            get {
                return ResourceManager.GetString("ChronoParamTypeDisplayNameIdleEngineRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коррекции инжекторов.
        /// </summary>
        public static string ChronoParamTypeDisplayNameInjectorCorrections {
            get {
                return ResourceManager.GetString("ChronoParamTypeDisplayNameInjectorCorrections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация учётной записи.
        /// </summary>
        public static string CleintRegistrationWindowHeader {
            get {
                return ResourceManager.GetString("CleintRegistrationWindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На клиентский ключ можно зарегистрировать только одну машину, поэтому в данном списке не будут отображены ключи с уже зарегистрированными на них машинами.
        /// </summary>
        public static string ClientKeyExplanatoryText {
            get {
                return ResourceManager.GetString("ClientKeyExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиентские ключи.
        /// </summary>
        public static string ClientKeysText {
            get {
                return ResourceManager.GetString("ClientKeysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрационные ключи для клиентов.
        /// </summary>
        public static string ClientRegistrationKeys {
            get {
                return ResourceManager.GetString("ClientRegistrationKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свободные ключи для клиентов.
        /// </summary>
        public static string ClientsFreeKeysText {
            get {
                return ResourceManager.GetString("ClientsFreeKeysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст комментария сохранится в базу после нажания Enter.
        /// </summary>
        public static string CommentTextSavingMessage {
            get {
                return ResourceManager.GetString("CommentTextSavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактные данные:.
        /// </summary>
        public static string ContactDataColon {
            get {
                return ResourceManager.GetString("ContactDataColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактные данные:.
        /// </summary>
        public static string ContactDataText {
            get {
                return ResourceManager.GetString("ContactDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактное лицо:.
        /// </summary>
        public static string ContactPersonColonText {
            get {
                return ResourceManager.GetString("ContactPersonColonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактное лицо:.
        /// </summary>
        public static string ContactPersonText {
            get {
                return ResourceManager.GetString("ContactPersonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        public static string ContinueText {
            get {
                return ResourceManager.GetString("ContinueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string CreateButtonText {
            get {
                return ResourceManager.GetString("CreateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string CreateText {
            get {
                return ResourceManager.GetString("CreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбран.
        /// </summary>
        public static string CurrentSelectedFileStubTextName {
            get {
                return ResourceManager.GetString("CurrentSelectedFileStubTextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный файл с данными:.
        /// </summary>
        public static string CurrentUploadedFileLabel {
            get {
                return ResourceManager.GetString("CurrentUploadedFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиенты.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при получении информации из базы данных.
        /// </summary>
        public static string DatabaseInformationRetrievalError {
            get {
                return ResourceManager.GetString("DatabaseInformationRetrievalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные для машины:.
        /// </summary>
        public static string DataContentsVehicleLabel {
            get {
                return ResourceManager.GetString("DataContentsVehicleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка введённых данных.
        /// </summary>
        public static string DataInputCheck {
            get {
                return ResourceManager.GetString("DataInputCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете просмотреть все сохранённые данные в разделе &quot;Данные&quot;. Для всей загруженной диагностической информации система автоматически вычислит хронологические параметры и выдаст предупреждения, коотрые вы можете просмотреть в соотвествующем разделе.
        /// </summary>
        public static string DataPersistedExplanation {
            get {
                return ResourceManager.GetString("DataPersistedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные сохранены.
        /// </summary>
        public static string DataPersistedHeader {
            get {
                return ResourceManager.GetString("DataPersistedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение данных в базу.
        /// </summary>
        public static string DataSaveToDatabase {
            get {
                return ResourceManager.GetString("DataSaveToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наборов данных в файле:.
        /// </summary>
        public static string DatasetsQuantityPerFileLabel {
            get {
                return ResourceManager.GetString("DatasetsQuantityPerFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наборы данных:.
        /// </summary>
        public static string DatasetsText {
            get {
                return ResourceManager.GetString("DatasetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор отображаемых данных.
        /// </summary>
        public static string DataTodisplayChoose {
            get {
                return ResourceManager.GetString("DataTodisplayChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дней до истечения.
        /// </summary>
        public static string DaysBeforeExpired {
            get {
                return ResourceManager.GetString("DaysBeforeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дней.
        /// </summary>
        public static string DaysText {
            get {
                return ResourceManager.GetString("DaysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используя выданный пользовательский ключ.
        /// </summary>
        public static string DeliveredKeyRadioButtonRegText {
            get {
                return ResourceManager.GetString("DeliveredKeyRadioButtonRegText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выданные конечным пользователям ключи.
        /// </summary>
        public static string DeliveredKeysText {
            get {
                return ResourceManager.GetString("DeliveredKeysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выданные.
        /// </summary>
        public static string DeliveredText {
            get {
                return ResourceManager.GetString("DeliveredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдан ли клиенту.
        /// </summary>
        public static string DeliveredToClient {
            get {
                return ResourceManager.GetString("DeliveredToClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробности.
        /// </summary>
        public static string DetailsText {
            get {
                return ResourceManager.GetString("DetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрационный ключ помечен как доставленный клиенту. Теперь на этот ключ может быть зарегистррована машина и внесены диагностические данные..
        /// </summary>
        public static string DgKyDlvdd {
            get {
                return ResourceManager.GetString("DgKyDlvdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диагностические данные.
        /// </summary>
        public static string DiagnosticData {
            get {
                return ResourceManager.GetString("DiagnosticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диагностические данные.
        /// </summary>
        public static string DiagnosticData1 {
            get {
                return ResourceManager.GetString("DiagnosticData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка диагностических данных.
        /// </summary>
        public static string DiagnosticDataUpload {
            get {
                return ResourceManager.GetString("DiagnosticDataUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail:.
        /// </summary>
        public static string EmailColonText {
            get {
                return ResourceManager.GetString("EmailColonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string EmailLabelText {
            get {
                return ResourceManager.GetString("EmailLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты не задан.
        /// </summary>
        public static string EmailNotSetErrorMessage {
            get {
                return ResourceManager.GetString("EmailNotSetErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эмитент.
        /// </summary>
        public static string EmitentText {
            get {
                return ResourceManager.GetString("EmitentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На пользователя, у которого ещё нет зарегистрированных машин.
        /// </summary>
        public static string EmptyUserRadioButtonRegText {
            get {
                return ResourceManager.GetString("EmptyUserRadioButtonRegText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конечные пользователи.
        /// </summary>
        public static string EndUsers {
            get {
                return ResourceManager.GetString("EndUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войдите в систему.
        /// </summary>
        public static string EnterTheSystem {
            get {
                return ResourceManager.GetString("EnterTheSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при создании ключа.
        /// </summary>
        public static string ErrorCreatingKey {
            get {
                return ResourceManager.GetString("ErrorCreatingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при сохранении данных.
        /// </summary>
        public static string ErrorSavingData {
            get {
                return ResourceManager.GetString("ErrorSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка. Попробуйте обновить или перелогиньтесь..
        /// </summary>
        public static string ErrorTryRefreshRelogin {
            get {
                return ResourceManager.GetString("ErrorTryRefreshRelogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просрочена.
        /// </summary>
        public static string ExpiredTextFem {
            get {
                return ResourceManager.GetString("ExpiredTextFem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как дополнительную для зарегистрированного пользователя.
        /// </summary>
        public static string ExtraVehicleRadioButtonRegText {
            get {
                return ResourceManager.GetString("ExtraVehicleRadioButtonRegText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть файл....
        /// </summary>
        public static string FileCloseButtonLabel {
            get {
                return ResourceManager.GetString("FileCloseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть файл....
        /// </summary>
        public static string FileUploadButtonLabel {
            get {
                return ResourceManager.GetString("FileUploadButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите файл с данными для загрузки:.
        /// </summary>
        public static string FileUploadRequestLabel {
            get {
                return ResourceManager.GetString("FileUploadRequestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При 1000 об/мин.
        /// </summary>
        public static string For1000Rpm {
            get {
                return ResourceManager.GetString("For1000Rpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При 2000 об/мин.
        /// </summary>
        public static string For2000Rpm {
            get {
                return ResourceManager.GetString("For2000Rpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При 3000 об/мин.
        /// </summary>
        public static string For3000Rpm {
            get {
                return ResourceManager.GetString("For3000Rpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вперёд.
        /// </summary>
        public static string ForwardText {
            get {
                return ResourceManager.GetString("ForwardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свободные ключи для регистрации партнёров.
        /// </summary>
        public static string FreePartnerKeysLabelText {
            get {
                return ResourceManager.GetString("FreePartnerKeysLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свободные регистрационные ключи.
        /// </summary>
        public static string FreePartnerRegistrationKeys {
            get {
                return ResourceManager.GetString("FreePartnerRegistrationKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свободные.
        /// </summary>
        public static string FreeText {
            get {
                return ResourceManager.GetString("FreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свободна.
        /// </summary>
        public static string FreeTextFem {
            get {
                return ResourceManager.GetString("FreeTextFem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общий срок действия.
        /// </summary>
        public static string GeneralPeriod {
            get {
                return ResourceManager.GetString("GeneralPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общий.
        /// </summary>
        public static string GeneralText {
            get {
                return ResourceManager.GetString("GeneralText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу импортировать.
        /// </summary>
        public static string ImportImpossibleCaption {
            get {
                return ResourceManager.GetString("ImportImpossibleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введён некорректный ключ, свяжитесь с поставщиком услуг для получения действительного регистрационного ключа..
        /// </summary>
        public static string IncorrectKeyProvidedText {
            get {
                return ResourceManager.GetString("IncorrectKeyProvidedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усреднённые по оборотам показатели коррекции форсунок дизельного двигателя. Вычисляются при наличии данных для 1000, 2000 и 3000 об/мин.
        /// </summary>
        public static string InjectorCorrectionsMedianValuesExplanatoryText {
            get {
                return ResourceManager.GetString("InjectorCorrectionsMedianValuesExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средние значения.
        /// </summary>
        public static string InjectorCorrectionsMedianValuesText {
            get {
                return ResourceManager.GetString("InjectorCorrectionsMedianValuesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предельные (мин. и макс.) показатели коррекции форсунок дизельного двигателя. Вычисляются отдельно для каждой форсунки при 1000, 2000 и 3000 об/мин.
        /// </summary>
        public static string InjectorCorrectionsRangeValuesExplanatoryText {
            get {
                return ResourceManager.GetString("InjectorCorrectionsRangeValuesExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предельные значения.
        /// </summary>
        public static string InjectorCorrectionsRangeValuesText {
            get {
                return ResourceManager.GetString("InjectorCorrectionsRangeValuesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции с запросами на выдачу лицензии.
        /// </summary>
        public static string IssuanceRequestOperationsText {
            get {
                return ResourceManager.GetString("IssuanceRequestOperationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запросы на выдачу.
        /// </summary>
        public static string IssuanceRequestsText {
            get {
                return ResourceManager.GetString("IssuanceRequestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ.
        /// </summary>
        public static string KeyColumnName {
            get {
                return ResourceManager.GetString("KeyColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключи, выданные клиентам.
        /// </summary>
        public static string KeysDeliveredToClientsText {
            get {
                return ResourceManager.GetString("KeysDeliveredToClientsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ.
        /// </summary>
        public static string KeyText {
            get {
                return ResourceManager.GetString("KeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение ключа.
        /// </summary>
        public static string KeyValueText {
            get {
                return ResourceManager.GetString("KeyValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to км.
        /// </summary>
        public static string KmText {
            get {
                return ResourceManager.GetString("KmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для создания ключа активируется одна свободная лицензия класса A.
        /// </summary>
        public static string LicenseAConsumptionExplanatoryText {
            get {
                return ResourceManager.GetString("LicenseAConsumptionExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to А — для регистрации пользователей или машин.
        /// </summary>
        public static string LicenseARadioButtonText {
            get {
                return ResourceManager.GetString("LicenseARadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класс лицензии:.
        /// </summary>
        public static string LicenseClassColonText {
            get {
                return ResourceManager.GetString("LicenseClassColonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензия для этой машины истекла. Продлить её вы можете на странице операций с лицензиями. Номер лицензии: №{0}.
        /// </summary>
        public static string LicenseExpirationMessageStub {
            get {
                return ResourceManager.GetString("LicenseExpirationMessageStub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to истекает через {0} дней.
        /// </summary>
        public static string LicenseExpirationPeriodDisplayStringFormat {
            get {
                return ResourceManager.GetString("LicenseExpirationPeriodDisplayStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to истекла {0} дней назад.
        /// </summary>
        public static string LicenseExpiredDaysStringFormat {
            get {
                return ResourceManager.GetString("LicenseExpiredDaysStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензия на продление:.
        /// </summary>
        public static string LicenseForProlongationText {
            get {
                return ResourceManager.GetString("LicenseForProlongationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка запроса на лицензию.
        /// </summary>
        public static string LicenseIssuanceRequestSend {
            get {
                return ResourceManager.GetString("LicenseIssuanceRequestSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаг 1. Выбор типа и периода лицензии.
        /// </summary>
        public static string LicenseIssuanceRequestStep1 {
            get {
                return ResourceManager.GetString("LicenseIssuanceRequestStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаг 2. Выбор количества нужных лицензий.
        /// </summary>
        public static string LicenseIssuanceRequestStep2 {
            get {
                return ResourceManager.GetString("LicenseIssuanceRequestStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаг 3. Подтверждение правильности данных.
        /// </summary>
        public static string LicenseIssuanceRequestStep3 {
            get {
                return ResourceManager.GetString("LicenseIssuanceRequestStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить запрос.
        /// </summary>
        public static string LicenseIssuanceSendRequest {
            get {
                return ResourceManager.GetString("LicenseIssuanceSendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензия №{0} .
        /// </summary>
        public static string LicenseNumberStringFormat {
            get {
                return ResourceManager.GetString("LicenseNumberStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период: {0} дней, .
        /// </summary>
        public static string LicensePeriodDisplayStringFormat {
            get {
                return ResourceManager.GetString("LicensePeriodDisplayStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период действия лицензии:.
        /// </summary>
        public static string LicensePeriodText {
            get {
                return ResourceManager.GetString("LicensePeriodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите лицензию из списка. Если вы аннулируете ключ, лицензия вернётся вам. Созданный ключ можно выдать клиенту, чтобы он смог зарегистрироваться в системе. На выданный ключ можно внести данные по машине, чтобы клиент после регистрации смог их просмотреть. Всегда помечайте ключ как выданный перед тем как доставить его клиенту, чтобы другой пользователь не выдал этот ключ другому клиенту..
        /// </summary>
        public static string LicensePickUpExplanatoryMessage {
            get {
                return ResourceManager.GetString("LicensePickUpExplanatoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здесь вы можете послать запрос на продление лицензии. Как только продление лицензии будет оплачено и администратор одобрит продление, лицензия снова станет активной..
        /// </summary>
        public static string LicenseProlongationExplanatoryText {
            get {
                return ResourceManager.GetString("LicenseProlongationExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продление лицензии.
        /// </summary>
        public static string LicenseProlongationText {
            get {
                return ResourceManager.GetString("LicenseProlongationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество лицензий:.
        /// </summary>
        public static string LicenseQuantityText {
            get {
                return ResourceManager.GetString("LicenseQuantityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Назад.
        /// </summary>
        public static string LicenseRequestBackText {
            get {
                return ResourceManager.GetString("LicenseRequestBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неудача. Попробуйте ещё раз, возможно проблемы с подключением к сети..
        /// </summary>
        public static string LicenseRequestFailureText {
            get {
                return ResourceManager.GetString("LicenseRequestFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее &gt;.
        /// </summary>
        public static string LicenseRequestFrowardText {
            get {
                return ResourceManager.GetString("LicenseRequestFrowardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос отправлен, его состояние вы можете проверить в разделе &quot;Статус моих запросов.&quot;.
        /// </summary>
        public static string LicenseRequestSentInformationText {
            get {
                return ResourceManager.GetString("LicenseRequestSentInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос на лицензию к выдаче:.
        /// </summary>
        public static string LicenseRequestToIssueText {
            get {
                return ResourceManager.GetString("LicenseRequestToIssueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензии.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции с лицензиями для регистрации клиентов и машин: запрос на получение и продление лицензий, просмотр выданных лицензий и их состояния .
        /// </summary>
        public static string LicensesExplanatoryText {
            get {
                return ResourceManager.GetString("LicensesExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензии выданы.
        /// </summary>
        public static string LicensesIssuedText {
            get {
                return ResourceManager.GetString("LicensesIssuedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  от {0:dd MMMM yyyy}.
        /// </summary>
        public static string LicenseStartDateStringFormat {
            get {
                return ResourceManager.GetString("LicenseStartDateStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензия.
        /// </summary>
        public static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос: лицензия {0} в количестве {1}.
        /// </summary>
        public static string LicReqQntt {
            get {
                return ResourceManager.GetString("LicReqQntt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте доступность имени чтобы продолжить регистрацию.
        /// </summary>
        public static string LoginAccessibilityCheckLabel {
            get {
                return ResourceManager.GetString("LoginAccessibilityCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин:.
        /// </summary>
        public static string LoginColon {
            get {
                return ResourceManager.GetString("LoginColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой логин некорректен или уже занят. Пожалуйста, выберите другой..
        /// </summary>
        public static string LoginInaccessibleLabel {
            get {
                return ResourceManager.GetString("LoginInaccessibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой логин некорректен или уже занят. Пожалуйста, выберите другой..
        /// </summary>
        public static string LoginIncorrectMessage {
            get {
                return ResourceManager.GetString("LoginIncorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин не задан.
        /// </summary>
        public static string LoginNotSetErrorMessage {
            get {
                return ResourceManager.GetString("LoginNotSetErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин уже занят.
        /// </summary>
        public static string LoginOccupiedErrorMessage {
            get {
                return ResourceManager.GetString("LoginOccupiedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин:.
        /// </summary>
        public static string LoginTextBlockText {
            get {
                return ResourceManager.GetString("LoginTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти в систему под новым аккаунтом после завершения.
        /// </summary>
        public static string LoginWithNewAcc {
            get {
                return ResourceManager.GetString("LoginWithNewAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в систему.
        /// </summary>
        public static string LogonHyperlinkButtonText {
            get {
                return ResourceManager.GetString("LogonHyperlinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход из системы.
        /// </summary>
        public static string LogoutHyperlinkButtonText {
            get {
                return ResourceManager.GetString("LogoutHyperlinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательные данные.
        /// </summary>
        public static string MadatoryDataText {
            get {
                return ResourceManager.GetString("MadatoryDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В выданные.
        /// </summary>
        public static string MarkKeyAsDeliveredButtonText {
            get {
                return ResourceManager.GetString("MarkKeyAsDeliveredButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усреднённые значения коррекций инжекторов.
        /// </summary>
        public static string MedianInjectorCorrDataHeader {
            get {
                return ResourceManager.GetString("MedianInjectorCorrDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пробег:.
        /// </summary>
        public static string MileageColon {
            get {
                return ResourceManager.GetString("MileageColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общий пробег:.
        /// </summary>
        public static string MileageLabel {
            get {
                return ResourceManager.GetString("MileageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензии в моём распоряжении.
        /// </summary>
        public static string MyLicensesText {
            get {
                return ResourceManager.GetString("MyLicensesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя:.
        /// </summary>
        public static string NameColon {
            get {
                return ResourceManager.GetString("NameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя:.
        /// </summary>
        public static string NameText1 {
            get {
                return ResourceManager.GetString("NameText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензии – доступные.
        /// </summary>
        public static string NavigatablePageHeaderAvailableLicenses {
            get {
                return ResourceManager.GetString("NavigatablePageHeaderAvailableLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиенты.
        /// </summary>
        public static string NavigatablePageHeaderClients {
            get {
                return ResourceManager.GetString("NavigatablePageHeaderClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные.
        /// </summary>
        public static string NavigatablePageHeaderData {
            get {
                return ResourceManager.GetString("NavigatablePageHeaderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ данных.
        /// </summary>
        public static string NavigatablePageHeaderDataAnalysis {
            get {
                return ResourceManager.GetString("NavigatablePageHeaderDataAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка данных.
        /// </summary>
        public static string NavigatablePageHeaderDataUpload {
            get {
                return ResourceManager.GetString("NavigatablePageHeaderDataUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочий стол.
        /// </summary>
        public static string NavigatablePageHeaderDesktop {
            get {
                return ResourceManager.GetString("NavigatablePageHeaderDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензии.
        /// </summary>
        public static string NavigatablePageHeaderLicenses {
            get {
                return ResourceManager.GetString("NavigatablePageHeaderLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнёры.
        /// </summary>
        public static string NavigatablePageHeaderPartners {
            get {
                return ResourceManager.GetString("NavigatablePageHeaderPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрационные ключи.
        /// </summary>
        public static string NavigatablePageHeaderRegKeys {
            get {
                return ResourceManager.GetString("NavigatablePageHeaderRegKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Машины.
        /// </summary>
        public static string NavigatablePageHeaderVehicles {
            get {
                return ResourceManager.GetString("NavigatablePageHeaderVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новый регистрационный ключ и внести данные на него.
        /// </summary>
        public static string NewKeyRadioButtonRegText {
            get {
                return ResourceManager.GetString("NewKeyRadioButtonRegText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные для импорта не выбраны. Выберите данные и повторите попытку..
        /// </summary>
        public static string NoDataSelectedForImport {
            get {
                return ResourceManager.GetString("NoDataSelectedForImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательные данные.
        /// </summary>
        public static string ObligatoryData {
            get {
                return ResourceManager.GetString("ObligatoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опциональные данные.
        /// </summary>
        public static string OptionalData {
            get {
                return ResourceManager.GetString("OptionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эти данные необязательно вводить сейчас, их можно заполнить в любое время после регистрации на странице пользовательского профиля..
        /// </summary>
        public static string OptionalDataReminderText {
            get {
                return ResourceManager.GetString("OptionalDataReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опциональные данные.
        /// </summary>
        public static string OptionalDataText {
            get {
                return ResourceManager.GetString("OptionalDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эти данные необязательно вводить сейчас, их можно заполнить в любое время после регистрации на странице пользовательского профиля..
        /// </summary>
        public static string OptionalRegDataMessage {
            get {
                return ResourceManager.GetString("OptionalRegDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация:.
        /// </summary>
        public static string OrganizationColon {
            get {
                return ResourceManager.GetString("OrganizationColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название организации не задано.
        /// </summary>
        public static string OrgNameNotSetErrorMessage {
            get {
                return ResourceManager.GetString("OrgNameNotSetErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество параметров:.
        /// </summary>
        public static string ParametersQuantityColon {
            get {
                return ResourceManager.GetString("ParametersQuantityColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнёрские ключи.
        /// </summary>
        public static string PartnerKeysText {
            get {
                return ResourceManager.GetString("PartnerKeysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции с лицензиями для партнёров.
        /// </summary>
        public static string PartnerLicensesOperationsText {
            get {
                return ResourceManager.GetString("PartnerLicensesOperationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание ключа для регистрации партнёра.
        /// </summary>
        public static string PartnerRegisterKeyEmissionWindowText {
            get {
                return ResourceManager.GetString("PartnerRegisterKeyEmissionWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация партнёрской учётной записи.
        /// </summary>
        public static string PartnerRegistrationWindowHeader {
            get {
                return ResourceManager.GetString("PartnerRegistrationWindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнёры.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список зарегистрированных партнёров, операции с партнёрскими учётными записями.
        /// </summary>
        public static string PartnersExplanatoryText {
            get {
                return ResourceManager.GetString("PartnersExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрированные машины.
        /// </summary>
        public static string PartnerVehiclesHeaderText {
            get {
                return ResourceManager.GetString("PartnerVehiclesHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запросивший партнёр:.
        /// </summary>
        public static string PartnerWhoHasRequestedText {
            get {
                return ResourceManager.GetString("PartnerWhoHasRequestedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль:.
        /// </summary>
        public static string PasswordColon {
            get {
                return ResourceManager.GetString("PasswordColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль:.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль:.
        /// </summary>
        public static string PasswordTextBlockText {
            get {
                return ResourceManager.GetString("PasswordTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон:.
        /// </summary>
        public static string PhoneColonText {
            get {
                return ResourceManager.GetString("PhoneColonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон:.
        /// </summary>
        public static string PhoneText {
            get {
                return ResourceManager.GetString("PhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнение профиля.
        /// </summary>
        public static string ProfileFilling {
            get {
                return ResourceManager.GetString("ProfileFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На какой срок будем продлевать?.
        /// </summary>
        public static string ProlongationPeriodQuestionText {
            get {
                return ResourceManager.GetString("ProlongationPeriodQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string ProlongationRequestAlreadyExists {
            get {
                return ResourceManager.GetString("ProlongationRequestAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос на продление этой лицензии уже отправлен, и второй не может быть создан пока не одобрен первый. Свяжитесь с администратором – возможно, это ускорит обработку запроса..
        /// </summary>
        public static string ProlongationRequestAlreadyExistsExplanation {
            get {
                return ResourceManager.GetString("ProlongationRequestAlreadyExistsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продление просроченных лицензий .
        /// </summary>
        public static string ProlongationRequestOperationsText {
            get {
                return ResourceManager.GetString("ProlongationRequestOperationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос на продление лицензии отправлен.
        /// </summary>
        public static string ProlongationRequestSent {
            get {
                return ResourceManager.GetString("ProlongationRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как только запрос будет одобрен, лицензия снова активируется и связанные с ней данные будут доступны для просмотра..
        /// </summary>
        public static string ProlongationRequestSentExplanation {
            get {
                return ResourceManager.GetString("ProlongationRequestSentExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запросы на продление.
        /// </summary>
        public static string ProlongationRequestsText {
            get {
                return ResourceManager.GetString("ProlongationRequestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продлить лицензию.
        /// </summary>
        public static string ProlongLicenseText {
            get {
                return ResourceManager.GetString("ProlongLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продлить.
        /// </summary>
        public static string ProlongText {
            get {
                return ResourceManager.GetString("ProlongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество запрошенных экземпляров:.
        /// </summary>
        public static string QuantityRequestedText {
            get {
                return ResourceManager.GetString("QuantityRequestedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коридор предельных значений коррекций инжекторов.
        /// </summary>
        public static string RangeInjectorCorrDataHeader {
            get {
                return ResourceManager.GetString("RangeInjectorCorrDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить список.
        /// </summary>
        public static string RefreshListText {
            get {
                return ResourceManager.GetString("RefreshListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string RefreshText {
            get {
                return ResourceManager.GetString("RefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрированные клиенты.
        /// </summary>
        public static string RegisteredClients {
            get {
                return ResourceManager.GetString("RegisteredClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрирован:.
        /// </summary>
        public static string RegisteredColon {
            get {
                return ResourceManager.GetString("RegisteredColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрированные партнёры.
        /// </summary>
        public static string RegisteredPartners {
            get {
                return ResourceManager.GetString("RegisteredPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрировано на.
        /// </summary>
        public static string RegisteredToText {
            get {
                return ResourceManager.GetString("RegisteredToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterHyperlinkButtonText {
            get {
                return ResourceManager.GetString("RegisterHyperlinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные о регистрируемой машине.
        /// </summary>
        public static string RegisteringVehicleData {
            get {
                return ResourceManager.GetString("RegisteringVehicleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрировать выбранным способом -&gt;.
        /// </summary>
        public static string RegisterSelectedWay {
            get {
                return ResourceManager.GetString("RegisterSelectedWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание регистрационного ключа.
        /// </summary>
        public static string RegistrationKeyCreation {
            get {
                return ResourceManager.GetString("RegistrationKeyCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдача ключа.
        /// </summary>
        public static string RegistrationKeyDeliveranceText {
            get {
                return ResourceManager.GetString("RegistrationKeyDeliveranceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат регистрационного ключа:.
        /// </summary>
        public static string RegistrationKeyFormatMessage {
            get {
                return ResourceManager.GetString("RegistrationKeyFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ, на который зарегистрирована машина, помечен как выданный клиенту. После регистрации в системе с этим ключом клиент сможет просмотреть сохранённые данные о своей машине..
        /// </summary>
        public static string RegistrationKeyForVehicleMessage {
            get {
                return ResourceManager.GetString("RegistrationKeyForVehicleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрационные ключи.
        /// </summary>
        public static string RegistrationKeys {
            get {
                return ResourceManager.GetString("RegistrationKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор регистрационного ключа.
        /// </summary>
        public static string RegistrationKeySelectionText {
            get {
                return ResourceManager.GetString("RegistrationKeySelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции с регистрационными ключами: cоздание рег. ключей (потребуется лицензия класса А), аннулирование ключей или установление отметки о выдаче ключа клиенту..
        /// </summary>
        public static string RegistrationKeysExplanatoryText {
            get {
                return ResourceManager.GetString("RegistrationKeysExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процесс регистрации.
        /// </summary>
        public static string RegistrationProcessText {
            get {
                return ResourceManager.GetString("RegistrationProcessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активация регистрационного ключа.
        /// </summary>
        public static string RegKeyActivation {
            get {
                return ResourceManager.GetString("RegKeyActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрационный ключ – уникальный идентификатор (GUID), который позволит системе распознать вас как пользователя и предоставить соответствующий уровень доступа после регистрации..
        /// </summary>
        public static string RegKeyExplanationText {
            get {
                return ResourceManager.GetString("RegKeyExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите ваш регистрационный ключ:.
        /// </summary>
        public static string RegKeyInputRequest {
            get {
                return ResourceManager.GetString("RegKeyInputRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string RemoveText {
            get {
                return ResourceManager.GetString("RemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запросить лицензию.
        /// </summary>
        public static string RequestForLicenseText {
            get {
                return ResourceManager.GetString("RequestForLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус моих запросов.
        /// </summary>
        public static string RequestsStatusText {
            get {
                return ResourceManager.GetString("RequestsStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс.
        /// </summary>
        public static string ResetText {
            get {
                return ResourceManager.GetString("ResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аннулирование ключа.
        /// </summary>
        public static string RKCancT {
            get {
                return ResourceManager.GetString("RKCancT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы собираетесь аннулировать выданный пользователю ключ. После этого пользователь не сможет использовать его для регистрации. Продолжить?.
        /// </summary>
        public static string RKCancWrn {
            get {
                return ResourceManager.GetString("RKCancWrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрационный ключ аннулирован. Лицензия деактивирована и снова доступна для использования..
        /// </summary>
        public static string RKCcldT {
            get {
                return ResourceManager.GetString("RKCcldT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аннулирование ключа.
        /// </summary>
        public static string RKyDctvt {
            get {
                return ResourceManager.GetString("RKyDctvt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранённые данные.
        /// </summary>
        public static string SavedData {
            get {
                return ResourceManager.GetString("SavedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ данных.
        /// </summary>
        public static string SavedDataAnalysis {
            get {
                return ResourceManager.GetString("SavedDataAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматический анализ сохранённых данных, слежение за изменениями параметров машины за время наблюдений.
        /// </summary>
        public static string SavedDataAnalysisExplanatoryText {
            get {
                return ResourceManager.GetString("SavedDataAnalysisExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить выбранное.
        /// </summary>
        public static string SaveSelectedButtonLabel {
            get {
                return ResourceManager.GetString("SaveSelectedButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите автомобиль из списка:.
        /// </summary>
        public static string SelectVehicleText {
            get {
                return ResourceManager.GetString("SelectVehicleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите машину из списка:.
        /// </summary>
        public static string SelectVehicleText1 {
            get {
                return ResourceManager.GetString("SelectVehicleText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка запроса.
        /// </summary>
        public static string SendingRequest {
            get {
                return ResourceManager.GetString("SendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to показать.
        /// </summary>
        public static string ShowPasswordButtonText {
            get {
                return ResourceManager.GetString("ShowPasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to показать.
        /// </summary>
        public static string ShowText {
            get {
                return ResourceManager.GetString("ShowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия:.
        /// </summary>
        public static string SurnameColon {
            get {
                return ResourceManager.GetString("SurnameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string SurnameText {
            get {
                return ResourceManager.GetString("SurnameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия:.
        /// </summary>
        public static string SurnameText1 {
            get {
                return ResourceManager.GetString("SurnameText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название:.
        /// </summary>
        public static string TitleColonText {
            get {
                return ResourceManager.GetString("TitleColonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В выданные.
        /// </summary>
        public static string ToDelivered {
            get {
                return ResourceManager.GetString("ToDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдать.
        /// </summary>
        public static string ToIssueText {
            get {
                return ResourceManager.GetString("ToIssueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить файл.
        /// </summary>
        public static string UnableToOpenFile {
            get {
                return ResourceManager.GetString("UnableToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружены незарегистрированные машины.
        /// </summary>
        public static string UnregiseredVehiclesDetected {
            get {
                return ResourceManager.GetString("UnregiseredVehiclesDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система не поддерживает внесение данных на незарегистрированную в системе машину, поэтому перед сохранением диагностической информации машину надо зарегистрировать одним из доступных способов. Кликните на данные по машине на экране &quot;Загрузка диагностических данных&quot;, чтобы зарегистрировать автомобиль. .
        /// </summary>
        public static string UnregiseredVehiclesDetectedExplanation {
            get {
                return ResourceManager.GetString("UnregiseredVehiclesDetectedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vin незарегистрированных машин:.
        /// </summary>
        public static string UnregiseredVehiclesListHeader {
            get {
                return ResourceManager.GetString("UnregiseredVehiclesListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка данных.
        /// </summary>
        public static string UploadData {
            get {
                return ResourceManager.GetString("UploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка данных в формате .vts, экспортированных из диагностической системы..
        /// </summary>
        public static string UploadDataExplanatoryText {
            get {
                return ResourceManager.GetString("UploadDataExplanatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход пользователя в систему.
        /// </summary>
        public static string UserLogonWindowTitle {
            get {
                return ResourceManager.GetString("UserLogonWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден. Проверьте введённые данные..
        /// </summary>
        public static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество значений:.
        /// </summary>
        public static string ValuesQuantityColon {
            get {
                return ResourceManager.GetString("ValuesQuantityColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить из базы данных сведения о зарегистрированных машинах.
        /// </summary>
        public static string VehicleDataRetrievalErrorMessage {
            get {
                return ResourceManager.GetString("VehicleDataRetrievalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получение данных о машине.
        /// </summary>
        public static string VehicleDataRetrievalInProgressMessage {
            get {
                return ResourceManager.GetString("VehicleDataRetrievalInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Машина не зарегистрирована в системе.
        /// </summary>
        public static string VehicleNotRegisteredHeader {
            get {
                return ResourceManager.GetString("VehicleNotRegisteredHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете увидеть её на экране зарегистрированных машин. На неё теперь могут быть внесены данные, которые станут доступны клиенту для просмотра после того, как он зарегистрируется в системе по выданному ему ключу..
        /// </summary>
        public static string VehicleRegisteredExplanatory1Text {
            get {
                return ResourceManager.GetString("VehicleRegisteredExplanatory1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При регистрации машины была задействована одна лицензия класса A – та же самая, что при создании регистрационного ключа. После регистрации пользователя вы сможете зарегистрировать на его имя дополнительные машины, это потребует лицензии класса А..
        /// </summary>
        public static string VehicleRegisteredExplanatory2Text {
            get {
                return ResourceManager.GetString("VehicleRegisteredExplanatory2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Машина зарегистрирована.
        /// </summary>
        public static string VehicleRegisteredText {
            get {
                return ResourceManager.GetString("VehicleRegisteredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация машины в базе данных.
        /// </summary>
        public static string VehicleRegistrationInDatabaseText {
            get {
                return ResourceManager.GetString("VehicleRegistrationInDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрировать машину в системе можно одним из следующих способов: .
        /// </summary>
        public static string VehicleRegistrationRequirementsText {
            get {
                return ResourceManager.GetString("VehicleRegistrationRequirementsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация автомобиля.
        /// </summary>
        public static string VehicleRegistrationText {
            get {
                return ResourceManager.GetString("VehicleRegistrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Машины.
        /// </summary>
        public static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транспортное средство.
        /// </summary>
        public static string VehicleText {
            get {
                return ResourceManager.GetString("VehicleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vin:.
        /// </summary>
        public static string VinLabel {
            get {
                return ResourceManager.GetString("VinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто запросил.
        /// </summary>
        public static string WhoHasRequestedText {
            get {
                return ResourceManager.GetString("WhoHasRequestedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа с базой данных.
        /// </summary>
        public static string WorkingWithDatabaseText {
            get {
                return ResourceManager.GetString("WorkingWithDatabaseText", resourceCulture);
            }
        }
    }
}
