//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWeb.Service.VtsWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainObjectDto", Namespace="http://schemas.datacontract.org/2004/07/VTSWebService.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTSWeb.Service.VtsWebService.AgentVersionDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTSWeb.Service.VtsWebService.VehicleDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VTSWeb.Service.VtsWebService.UserDto))]
    public partial class DomainObjectDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentVersionDto", Namespace="http://schemas.datacontract.org/2004/07/VTSWebService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class AgentVersionDto : VTSWeb.Service.VtsWebService.DomainObjectDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DownloadLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReleasedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DownloadLink {
            get {
                return this.DownloadLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.DownloadLinkField, value) != true)) {
                    this.DownloadLinkField = value;
                    this.RaisePropertyChanged("DownloadLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReleasedDate {
            get {
                return this.ReleasedDateField;
            }
            set {
                if ((this.ReleasedDateField.Equals(value) != true)) {
                    this.ReleasedDateField = value;
                    this.RaisePropertyChanged("ReleasedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VersionString {
            get {
                return this.VersionStringField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionStringField, value) != true)) {
                    this.VersionStringField = value;
                    this.RaisePropertyChanged("VersionString");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleDto", Namespace="http://schemas.datacontract.org/2004/07/VTSWebService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class VehicleDto : VTSWeb.Service.VtsWebService.DomainObjectDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductionYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegisteredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VinField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Manufacturer {
            get {
                return this.ManufacturerField;
            }
            set {
                if ((this.ManufacturerField.Equals(value) != true)) {
                    this.ManufacturerField = value;
                    this.RaisePropertyChanged("Manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((this.MileageField.Equals(value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductionYear {
            get {
                return this.ProductionYearField;
            }
            set {
                if ((this.ProductionYearField.Equals(value) != true)) {
                    this.ProductionYearField = value;
                    this.RaisePropertyChanged("ProductionYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegisteredDate {
            get {
                return this.RegisteredDateField;
            }
            set {
                if ((this.RegisteredDateField.Equals(value) != true)) {
                    this.RegisteredDateField = value;
                    this.RaisePropertyChanged("RegisteredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vin {
            get {
                return this.VinField;
            }
            set {
                if ((object.ReferenceEquals(this.VinField, value) != true)) {
                    this.VinField = value;
                    this.RaisePropertyChanged("Vin");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/VTSWebService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class UserDto : VTSWeb.Service.VtsWebService.DomainObjectDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegisteredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegisteredDate {
            get {
                return this.RegisteredDateField;
            }
            set {
                if ((this.RegisteredDateField.Equals(value) != true)) {
                    this.RegisteredDateField = value;
                    this.RaisePropertyChanged("RegisteredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VtsWebService.IVtsWebService")]
    public interface IVtsWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/CheckConnection", ReplyAction="http://tempuri.org/IVtsWebService/CheckConnectionResponse")]
        string CheckConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/CheckUsernameAvailability", ReplyAction="http://tempuri.org/IVtsWebService/CheckUsernameAvailabilityResponse")]
        bool CheckUsernameAvailability(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/AuthenticateUser", ReplyAction="http://tempuri.org/IVtsWebService/AuthenticateUserResponse")]
        VTSWeb.Service.VtsWebService.UserDto AuthenticateUser(string login, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetLastAgentVersion", ReplyAction="http://tempuri.org/IVtsWebService/GetLastAgentVersionResponse")]
        VTSWeb.Service.VtsWebService.AgentVersionDto GetLastAgentVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/RegisterUser", ReplyAction="http://tempuri.org/IVtsWebService/RegisterUserResponse")]
        void RegisterUser(VTSWeb.Service.VtsWebService.UserDto user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetUserRoleByUserId", ReplyAction="http://tempuri.org/IVtsWebService/GetUserRoleByUserIdResponse")]
        int GetUserRoleByUserId(long userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetPartnersVehiclesCount", ReplyAction="http://tempuri.org/IVtsWebService/GetPartnersVehiclesCountResponse")]
        int GetPartnersVehiclesCount(long partnerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetClientsForPartner", ReplyAction="http://tempuri.org/IVtsWebService/GetClientsForPartnerResponse")]
        VTSWeb.Service.VtsWebService.UserDto[] GetClientsForPartner(string login, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVtsWebService/GetUsersVehicles", ReplyAction="http://tempuri.org/IVtsWebService/GetUsersVehiclesResponse")]
        VTSWeb.Service.VtsWebService.VehicleDto[] GetUsersVehicles(string login, string passwordHash);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVtsWebServiceChannel : VTSWeb.Service.VtsWebService.IVtsWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VtsWebServiceClient : System.ServiceModel.ClientBase<VTSWeb.Service.VtsWebService.IVtsWebService>, VTSWeb.Service.VtsWebService.IVtsWebService {
        
        public VtsWebServiceClient() {
        }
        
        public VtsWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VtsWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VtsWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VtsWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckConnection() {
            return base.Channel.CheckConnection();
        }
        
        public bool CheckUsernameAvailability(string username) {
            return base.Channel.CheckUsernameAvailability(username);
        }
        
        public VTSWeb.Service.VtsWebService.UserDto AuthenticateUser(string login, string passwordHash) {
            return base.Channel.AuthenticateUser(login, passwordHash);
        }
        
        public VTSWeb.Service.VtsWebService.AgentVersionDto GetLastAgentVersion() {
            return base.Channel.GetLastAgentVersion();
        }
        
        public void RegisterUser(VTSWeb.Service.VtsWebService.UserDto user) {
            base.Channel.RegisterUser(user);
        }
        
        public int GetUserRoleByUserId(long userId) {
            return base.Channel.GetUserRoleByUserId(userId);
        }
        
        public int GetPartnersVehiclesCount(long partnerId) {
            return base.Channel.GetPartnersVehiclesCount(partnerId);
        }
        
        public VTSWeb.Service.VtsWebService.UserDto[] GetClientsForPartner(string login, string passwordHash) {
            return base.Channel.GetClientsForPartner(login, passwordHash);
        }
        
        public VTSWeb.Service.VtsWebService.VehicleDto[] GetUsersVehicles(string login, string passwordHash) {
            return base.Channel.GetUsersVehicles(login, passwordHash);
        }
    }
}
